services:
  backend:
    build:
      context: ..
      dockerfile: infra/Dockerfile.backend
    env_file:
      - ../.env
    ports:
      - "3000:3000"
    restart: unless-stopped

  hedger:
    build:
      context: ..
    # если вы уже переделали Dockerfile.hedger на deps→build→runtime — оставляем как есть:
      dockerfile: infra/Dockerfile.hedger
    env_file:
      - ../.env
    depends_on:
      - backend
    restart: unless-stopped
