name: ci

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'pnpm'   # кэш работает в связке с pnpm/action-setup

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.15.0   # зафиксируй версию, можно 'latest'

      - name: Show versions
        run: |
          node -v
          pnpm -v

      - name: Install deps (workspace)
        run: pnpm -w install --frozen-lockfile

      - name: Lint
        run: pnpm -w run lint

      - name: Test backend
        run: pnpm --filter backend-ts test

      - name: Test hedger
        run: pnpm --filter hedger test
