name: ci

on:
  push:
    branches: [ "main" ]
  pull_request:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node & pnpm
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
          cache: "pnpm"

      - name: Enable pnpm
        run: |
          corepack enable
          corepack prepare pnpm@latest --activate
          pnpm -v
          node -v

      - name: Install deps (workspace)
        run: pnpm -w install --frozen-lockfile

      - name: Lint
        run: pnpm -w run lint

      - name: Test backend
        run: pnpm --filter backend-ts test

      - name: Test hedger
        run: pnpm --filter hedger test

  docker-build:
    runs-on: ubuntu-latest
    needs: build-test

    steps:
      - uses: actions/checkout@v4
      - name: Build Docker images (no push)
        run: |
          docker build -f infra/Dockerfile.backend -t backend-ts:ci .
          docker build -f infra/Dockerfile.hedger -t hedger:ci .
